name: Phpstan + php-cs-fixer + composer validate
on: [push, pull_request]
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches composer cache folder & vendor folder
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'

      - run: |
          composer --version | grep '2\.[0-9]' --silent || (echo 'version de composer invalide';composer --version;exit 1 )
          composer --version && composer install -o

      - name : run tasks
        run: composer run-script pre-commit
