name: Phpstan + php-cs-fixer + composer validate
on: [push, pull_request]
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prestashop-version: [ '1.7.5.0', '1.7.5.2', '1.7.6.9', '1.7.7.4' ]
        php-version: ['7.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches composer cache folder & vendor folder
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            vendor
            ${{ runner.temp }}/prestashop_${{ matrix.prestashop-version }}
          key: php-${{ hashFiles('composer.lock') }}-${{ matrix.prestashop-version }}

      - name: Caches prestashop folder
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/prestashop_${{ matrix.prestashop-version }}
          key: prestashop-${{ matrix.prestashop-version }}
        id: cache_prestashop_source


      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'

      - run: composer install --no-dev -o

      - name: "Extract Prestashop"
        if: steps.cache_prestashop_source.outputs.cache-hit != 'true'
        run: |
          echo "no cache for Prestashop ${{ matrix.prestashop-version }} source. Fectching and extracting source code..."
          wget https://github.com/PrestaShop/PrestaShop/releases/download/${{ matrix.prestashop-version }}/prestashop_${{ matrix.prestashop-version }}.zip --quiet --output-document ${{ runner.temp }}/prestashop.zip
          unzip -q ${{ runner.temp }}/prestashop.zip -d ${{ runner.temp }}/prestashop_zip
          unzip -q ${{ runner.temp }}/prestashop_zip/prestashop.zip -d ${{ runner.temp }}/prestashop_${{ matrix.prestashop-version }}

      - name : run tasks
        run: |
          _PS_ROOT_DIR_=${{ runner.temp }}/prestashop_${{ matrix.prestashop-version }} ./vendor/bin/phpstan analyse
          ./vendor/bin/php-cs-fixer fix --dry-run --ansi
          composer validate
